### ISSUE TITLE
Browser support ?

### ISSUE THREAD

**Issue by revskill10** [overlookmotel/react-async-ssr#52] opened 2020-01-08 12:08 UTC
Does the library support browser rendering in future ?

**Comment by overlookmotel** [comment] 2020-01-08 17:55
Sorry, I don't really understand your question. This package is specifically designed for server-side rendering. React itself can do everything this module can in the browser already.

Or am I missing the point?

**Comment by revskill10** [comment] 2020-01-09 10:13
I tried to use `renderToStringAsync` on a React Component, but in browser, i got error about only-node dependencies is allowed. My React Component contains Suspense component with graphql data so i couldn't use default React's `renderToString` in this case.

**Comment by overlookmotel** [comment] 2020-01-10 13:07
Can't you just use `React.render()` to render the React component to a DOM element?

Why do you need to render to HTML?

**Comment by overlookmotel** [comment] 2020-01-10 13:13
This package's only dependency is `react-dom`, which works in browser. However this module does call `ReactDOM.renderToNodeStream()` - I guess that requires Node's native `stream` module within `react-dom`, hence the error you're getting.

I don't know how you've set up your browser bundle generation. But possibly you could get around this by telling webpack to use a browser-compatible alternative to Node's `stream` module e.g. [readable-stream](https://www.npmjs.com/package/readable-stream).

But, to be honest, I still don't understand what you're trying to achieve here.

**Comment by revskill10** [comment] 2020-01-11 12:48
@overlookmotel Because i want to retrive html content on browser from async React component. ReactDOMServer is synchronous so i couldn't get the html with async data, that's why i want to use `renderToStringAsync` on browser. The purpose is to convert html to pdf in my case.

**Comment by overlookmotel** [comment] 2020-01-11 13:31
Ah I see. Now I understand.

I suspect the problem is what I said above - `react-dom/server`'s `.renderToNodeStream()` method, which this package uses internally, will not work in browser, due to reliance on Node's native `stream` module. The [React docs](https://reactjs.org/docs/react-dom-server.html) say this is the case.

There's no way to remove the use of `ReactDomServer.renderToNodeStream()` in this module.

So I think only solution is to tell Webpack to substitute a browser-compatible alternative to Node's `stream` module e.g. [readable-stream](https://www.npmjs.com/package/readable-stream).

I can't advise you exactly how to do this, but I believe it's possible. You'd have to consult the docs for Webpack (or whatever other browser bundler you use).

Please let me know if you have success.

**Comment by overlookmotel** [comment] 2020-01-11 13:33
Another workaround would be to use `ReactDOM.render()` to render the component into a hidden div, and then read the HTML from the DOM with `.innerHTML`. A bit of a hack, but could work.

**Comment by revskill10** [comment] 2020-01-11 20:05
@overlookmotel Thanks for the feedback, i'll try both ways. I think why not creating another package for browser suppport, like `react-async-ssr/browser` ?

**Comment by overlookmotel** [comment] 2020-01-11 22:59
@revskill Unfortunately, due to the way React is built, it would require a lot of work to make a self-contained browser build.

Your use case is valid, but the core aim of this package is to enable server-side rendering (that's what the "SSR" in the name is), so I'm afraid I'm not willing to undertake that work to support a fairly niche case.

I'm going to close this issue now, but please do shout back with your findings about how you do/don't manage to get this working.

**Closed by overlookmotel** 2020-01-11 22:59 UTC

**Comment by revskill10** [comment] 2020-01-23 09:56
@overlookmotel Ah, i found the solution. I putthe `onClick` handler inside the Suspended component and just use normal `renderToString` there to retrieve html data, because the React component is already got its data :)

**Comment by overlookmotel** [comment] 2020-01-23 11:22
@revskill10 Interesting. Thanks for letting me know your solution.
