### ISSUE TITLE
Any way to create component that loads once per app render

### ISSUE THREAD

**Issue by dotterian** [overlookmotel/react-async-ssr#8] opened 2019-03-06 15:57 UTC
I'm looking for a way for component to run loading Promise on each render.
For now I have something similar to this:
```typescript
// Reading this on frontend to prevent duplicate fetches and rerender
let loaded = typeof window !== 'undefined' ? window.__loaded : false

class App extends Component {

  protected load = () => {
    return performFirstFetch()
      .then(() => performSecondFetch())
      .then(() => {
        loaded = true
        resolve()
      })
  }

  public render() {
    if (!loaded) {
      throw this.load()
    }
    /* actual rendering here, including <script>window.__loaded = true</script> */
  }
}
```
This code runs on first page load and doesn't run on all consecutive loads since variable `loaded` is defined in module and module is imported on server start.

I've tried to use class properties and state to store load info with no success: each time promise is resolved and render is called my `loaded` variable resets to `false`. Seems like component is reinitialized each time it's about to render. From a quick glance at render code I suspect problems occur at the moment of shimming element.

If my guess is correct, than I think this should be fixed since we all know it's not the way React renders it's DOM.

**Comment by overlookmotel** [comment] 2019-03-06 16:44
I'll have a look at this soon as I can.

One quick question: This is rendering on server side right?

**Comment by dotterian** [comment] 2019-03-06 16:51
Yes, this is server side problem.

**Comment by overlookmotel** [comment] 2019-03-06 17:55
Thanks for clarifying. Can you also please post the full code of `render()`, just to make it easier for me to replicate.

**Comment by dotterian** [comment] 2019-03-07 08:53
Ok, so I've made test components just to replicate my problem. (But I didn't have any chance to actually test them, so I'll just hope that they work as expected)

My goal is to call `load` on each page load/component render since data in API can change and user should get latest data.

This one works as expected but calls `load()` only on first render of component, so we would get stale data on all subsequent renders:
```typescript
let loaded = false

class LoadsOnce extends Component {

  protected load = () => {
    console.log('Calling promise')
    return new Promise(resolve => setTimeout(() => {
      console.log('Promise resolved')
      loaded = true
      resolve()
    }, 1000))
  }

  public render() {
    console.log('Trying to render component')
    if (!loaded) {
      throw this.load()
    }
    console.log('Actually rendering component')
    return <div>
      It worked!
    </div>
  }
}
```

This two components will call `load` endlessly, because component state resets on each render.
(On the other side fetched data is fresh as alpine air, if only it could get rendered somehow)
```typescript
class EndlessLoadUsingClassProperty extends Component {

  protected loaded = false

  protected load = () => {
    console.log('Calling promise')
    return new Promise(resolve => setTimeout(() => {
      console.log('Promise resolved')
      this.loaded = true
      resolve()
    }, 1000))
  }

  public render() {
    console.log('Trying to render component')
    if (!this.loaded) {
      throw this.load()
    }
    console.log('Actually rendering component')
    return <div>
      It worked!
    </div>
  }
}
```

```typescript
class EndlessLoadUsingComponentState extends Component {

  public state = {
    loaded: false
  }

  protected load = () => {
    console.log('Calling promise')
    return new Promise(resolve => setTimeout(() => {
      console.log('Promise resolved')
      this.setState({
        loaded: true
      })
      resolve()
    }, 1000))
  }

  public render() {
    console.log('Trying to render component')
    if (!this.state.loaded) {
      throw this.load()
    }
    console.log('Actually rendering component')
    return <div>
      It worked!
    </div>
  }
}
```

Also seems that setState callback isn't called
```javascript
this.setState({
  loaded: true
}, () => resolve())
```
Didn't resolve at all :C

**Comment by dotterian** [comment] 2019-03-11 11:18
I finally found the source of problem:
State and class properties exist only in instance that is created on initial render of async component and aren't stored anywhere.
Maybe you should add instance here:
```javascript
handlePromise(element, promise, instance) {
  /* [...] */
  const child = this.createChild(TYPE_PROMISE);
  child.element = element;
  child.promise = promise;
  child.instance = instance;

  this.lazyNodes.push(child);
}
```
And use instance's render method on second render to preserve state and class props.

**Comment by dotterian** [comment] 2019-03-11 11:34
Ok, I see where the real problem is:
`ReactDOMServerRenderer.render` relies on stateless "element" rather than stateful "instance".

In the end it seems that to solve my problem I either need to create and use context to track state of my async components, or completely rewrite React's `render`.
That's not great.

Hoping that support for Suspense in official ReactDOMServerRenderer, promised in React Roadmap somewhere in 2019, will come with support for stateful components. And that it releases soon.

**Comment by overlookmotel** [comment] 2019-03-14 15:25
@dotterian Sorry I'm slow to come back to you on this. Been crazy busy at work.

You are right that when an element throws a Promise, after the promise is resolved, the element is re-rendered, creating a new instance.

This is by design. It is the same behavior that React has on the client-side.

Also, state cannot change over time on a server render. On the client side, the page lives for some time and so can react to events and change the DOM. On server side, the page is rendered once to HTML and then sent to the client.

Your original example has `loaded` in global scope. So it will not be reset to `false` on each server-side render.

The solution, as you said, is to use `Context` to wrap the app and use that to create new state for each render. That `Context` can also be used to record the data that is loaded on server side, in order to then send it to the client for rehydration.

It should not be necessary to rewrite or monkey-patch React's render method.

Overall, what you're trying to do is very complicated. There are a lot of edge cases and moving parts (hence why React's official solution, `react-cache`, is still a work in progress). I'm working on a module that will handle all of this. But it won't be ready to release for probably another month.

If you make further progress in the meantime, please do reply here. I'd be very interested to hear any ideas you have.

**Comment by overlookmotel** [comment] 2019-03-18 23:57
I'm going to close this issue as I think my comment above answers the issue.

But please feel free to comment here further or open another issue if you find a problem beyond what's described in this issue.

**Closed by overlookmotel** 2019-03-18 23:57 UTC

**Comment by overlookmotel** [comment] 2020-04-06 00:05
@dotterian Best part of a year later, and I've finally solved the problem of async loading data on the server side.

You've probably moved on from trying to get this working long ago, but in case you're interested, here it is:

[react-lazy-data](https://www.npmjs.com/package/react-lazy-data)
